### ISSUE TITLE
Not working in 9.1

### ISSUE THREAD

**Issue by RenaKunisaki** [Cuyler36/Ghidra-GameCube-Loader#34]
Importing a .dol file fails:

```
Import File - Uncaught Exception: java.lang.NoClassDefFoundError: ghidra/app/util/importer/MemoryConflictHandler
java.lang.NoClassDefFoundError: ghidra/app/util/importer/MemoryConflictHandler
	at gamecubeloader.GameCubeLoader.loadProgram(GameCubeLoader.java:139)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:401)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:351)
	at ghidra.util.task.TaskLauncher$1.run(TaskLauncher.java:90)
	at ghidra.util.task.Task.monitoredRun(Task.java:126)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$1(TaskRunner.java:94)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: ghidra.app.util.importer.MemoryConflictHandler
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 10 more

---------------------------------------------------
Build Date: 2020-Feb-12 1149 EST
Ghidra Version: 9.1.2
Java Home: /usr/lib/jvm/java-11-openjdk
JVM Version: Oracle Corporation 11.0.6
OS: Linux 5.5.10-arch1-1 amd64
Workstation: gabumon
```

**Comment by Cuyler36** [comment]
Please give more context. What dol file are you trying to load? Is it a GameCube one, Wii one? Wii isn't officially supported by this loader.

**Comment by RenaKunisaki** [comment]
It's the main.dol from Mario Kart: Double Dash, US version.

**Comment by Cuyler36** [comment]
I'll take a look into it as soon as I can. I'm not really sure what the error is. I know for a fact it loads other DOLs properly in 9.1.2.

**Comment by RenaKunisaki** [comment]
This looks like the same issue:
https://github.com/Adubbz/Ghidra-Switch-Loader/issues/16

**Comment by RenaKunisaki** [comment]
??? I'm still getting this error with the latest commit
